#Компоуз для запуска всех сервисов
services:
  db:
    container_name: liquiDb
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "liqui"
      POSTGRES_USER: "pg"
      POSTGRES_PASSWORD: "pg"
    networks:
      - liquibase-k8s-net
    ports:
      - "5432:5432"

networks:
  liquibase-k8s-net:
    external: true